#生产环境
spring:
  profiles: prd
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.96.45.172:3306/dpm_ym_prd?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: dpm
    password: FUMEIYU!_dpm!_2017!
  redis:
      ###Redis数据库索引默认0
      database: 0
      host: 192.168.0.175
      port: 6379
      password: fumeiyu@08
      jedis:
        pool:
          ###连接池最大连接数
          max-active: 8
          ###连接池最大阻塞等待时间
          max-wait: -1
          ###连接池中的最大空闲连接
          max-idle: 5
          ###连接池中的最小空闲连接
          min-idle: 0
      ###连接超时时间(毫秒)
      timeout: 10000