spring:
  application:
    name: web-service
  profiles:
      active: @profileActive@
  #============================== ZIPKIN 调用链，开发时可注掉 ==================================
  zipkin:
    base-url: http://localhost:9411
    enabled: true
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0  #zipkin采集率  0.1表示 10%采集率
  http:
      encoding:
        charset: UTF-8
        force: true
        enabled: true
  servlet:
    multipart:
      maxFileSize: -1
      maxRequestSize: -1
server:
  port: 18991

logging:
  level:
    com.web-service: DEBUG

mybatis:
  mapper-locations: classpath:mapper/*.xml
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

eureka:
  client:
    service-url:
      defaultZone: http://localhost:18761/eureka/

# 配置swagger
swagger:
  title: API接口文档
  description: web
  version: 1.0.0
  termsOfServiceUrl: http://blog.csdn.net
  contact:
    name: web
    url: http://blog.csdn.net
    email:

#feign:
 # hystrix:
   # enabled: true      #启动断路器先关了要用自己开

